CREATE DATABASE gshepurc_buddialogue;

USE gshepurc_buddialogue;

CREATE TABLE BUDDIES(
BUDDY_ID INT NOT NULL auto_increment,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
NICK_NAME VARCHAR(30),
E_MAIL_ID VARCHAR(50),
USER_ID VARCHAR(30),
PASSWORD VARCHAR(20),
ACC_ENABLED CHAR(1),
SEX CHAR(1),
PRIMARY KEY (BUDDY_ID)
);

CREATE TABLE DIALOGUE
(
DIALOGUE_ID INT NOT NULL auto_increment,
DIALOGUE VARCHAR(1024),
WHO_CREATED INT,
WHOSE_DIALOGUE_BUDDY INT,
WHOSE_DIALOGUE_JUST_NAME VARCHAR(30),
WHEN_CREATED DATETIME,
PRIMARY KEY (DIALOGUE_ID),
CONSTRAINT FK1_DLG_BUD FOREIGN KEY (WHO_CREATED) REFERENCES BUDDIES(BUDDY_ID)
);

CREATE TABLE COMMENTS
(
COMMENT_ID INT NOT NULL auto_increment,
DIALOGUE_ID INT,
COMMENT VARCHAR(125),
WHO_COMMENTED INT,
WHEN_COMMENTED DATETIME,
PRIMARY KEY (COMMENT_ID),
CONSTRAINT FK1_CMT_DLG FOREIGN KEY (DIALOGUE_ID) REFERENCES DIALOGUE(DIALOGUE_ID),
CONSTRAINT FK2_CMT_DLG FOREIGN KEY (WHO_COMMENTED) REFERENCES BUDDIES(BUDDY_ID)
);

CREATE TABLE GROUPS
(
GROUP_ID INT NOT NULL auto_increment,
GROUP_NAME VARCHAR(50),
DESCRIPTION VARCHAR(125),
WHO_CREATED INT,
WHEN_CREATED DATETIME,
PRIMARY KEY (GROUP_ID),
CONSTRAINT FK1_GP_BUD FOREIGN KEY (WHO_CREATED) REFERENCES BUDDIES(BUDDY_ID)
);

CREATE TABLE GROUPS_BUDDIES
(
GROUP_ID INT,
BUDDY_ID INT,
PRIMARY KEY (GROUP_ID, BUDDY_ID),
CONSTRAINT FK1_GP_BUD_GP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID),
CONSTRAINT FK2_GP_BUD_BUD FOREIGN KEY (BUDDY_ID) REFERENCES BUDDIES(BUDDY_ID)
);

CREATE TABLE INVITATION
(
INVITATION_ID VARCHAR(30) NOT NULL,
E_MAIL_ID VARCHAR(50),
WHO_INVITED INT,
ACCEPTED CHAR(1),
FOR_WHICH_GP INT,
PRIMARY KEY (INVITATION_ID),
CONSTRAINT FK1_INV_BUD FOREIGN KEY (WHO_INVITED) REFERENCES BUDDIES(BUDDY_ID),
CONSTRAINT FK2_INV_GP FOREIGN KEY (FOR_WHICH_GP) REFERENCES GROUPS(GROUP_ID)
);

CREATE TABLE DIALOGUE_LIKES
(
DIALOGUE_ID INT,
BUDDY_ID INT,
PRIMARY KEY (DIALOGUE_ID,BUDDY_ID ),
CONSTRAINT FK1_DLG_LIKE_DLG FOREIGN KEY (DIALOGUE_ID) REFERENCES DIALOGUE(DIALOGUE_ID),
CONSTRAINT FK2_DLG_LIKE_BUD FOREIGN KEY (BUDDY_ID) REFERENCES BUDDIES(BUDDY_ID)
);

CREATE TABLE ROLES
(
ROLE_ID INT NOT NULL auto_increment,
ROLE_DESC VARCHAR(20),
PRIMARY KEY (ROLE_ID)
);

CREATE TABLE BUDDY_ROLES
(
BUDDY_ID INT,
ROLE_ID INT,
PRIMARY KEY (BUDDY_ID, ROLE_ID),
CONSTRAINT FK1_BUD_ROL_BUD FOREIGN KEY (BUDDY_ID) REFERENCES BUDDIES(BUDDY_ID),
CONSTRAINT FK2_BUD_ROL_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

insert into BUDDIES(FIRST_NAME,LAST_NAME,NICK_NAME,E_MAIL_ID,USER_ID,PASSWORD,ACC_ENABLED, SEX) values ('SSO', NULL, NULL,'sso@gshepur.com','sso','admin','y','m');
insert into BUDDIES(FIRST_NAME,LAST_NAME,NICK_NAME,E_MAIL_ID,USER_ID,PASSWORD,ACC_ENABLED, SEX) values ('Ram', NULL, NULL,'ram@gshepur.com','ram','ram12','y','m');
